f=open('output.txt','w')
x=input('Enter text to write to the file:')
f.write(x+'\n')
f.close()
print('Data successfully written to output.txt')
f.close()
f=open('output.txt','a')
y=input('Enter additional text to append:')
f.write(y)
print('Data successfully appended')
print('Final contents of output.txt')
f.close()
f=open('output.txt','r')
print(f.read())
f.close()